### ISSUE TITLE
Multiple P or S travel times in localization of local events/ 3D velocity model

### ISSUE THREAD

**Issue by Cthuulhaa** [alomax/NonLinLoc#11]
Hello Anthony,

I have two questions:

1.- When localizing local seismicity, what does NLL do if multiple phases are picked (e.g. Pn and Pg on the same station)? Does it use only one of them for the hypocenter calculation?

2.- What needs to be modified in the control file in order to use a 3D velocity model for the hypocenter calculation?

All the best,
Catalina

**Comment by alomax** [comment]
Hello Catalina

NLL can handle specific phases beyond P and S if you can calculate the times for each phase, and the wavetype (phase) label for the travel-time file matches the pick file phase type or its LOCPHASEID mapping.

Grid2Time (Podvin-Lecomte) only generates calculated times for first-arrivals, so typically this means Pg at closer distances and Pn at larger distance. So usually I set the Grid2Time phase type as P [or S]  and use LOCPHASEID to map all first P or S picks to "P" or "S", e.g.
LOCPHASEID  P   P Pg Pn
LOCPHASEID  S   S Sg Sn

But in this case if there is a Pg and a Pn, one of them would not correspond the calculated travel-times. I would have to test what would happen, but I suspect they well both be used and one will have a large residual - if you test this case it would be useful to know how the phases are used...

The LOCMETH control statement also has a flag to reject (1) or use (0) duplicate arrivals with the same station code and phase (if the time difference is less than the pick uncertainty, the second pick is always rejected):
LOCMETH iRejectDuplicateArrivals - flag to reject duplicate arrival observations (default if not present = 1)

Anthony

**Comment by alomax** [comment]
Oh, sorry! Please take a look here for a start: https://github.com/alomax/NonLinLoc/blob/master/doc/Gempa_ALomax__Use_of_3D_models_within_NLL_05.pdf
Anthony

**Comment by Cthuulhaa** [comment]
Oh, thanks! I had not seen that documentation.

I will close the issue now.

All the best,
Catalina
