### ISSUE TITLE
Hypocenter quality

### ISSUE THREAD

**Issue by Cthuulhaa** [alomax/NonLinLoc#12]
Hello Anthony,

I suppose that one can decide if the obtained hypocenter is reasonable/correct by looking in the .grid0.loc.hyp, line 8 (QUALITY).

For example, this is what I obtained for one location:

`QUALITY  Pmax 4.06675e+113 MFmin 54.8605 MFmax 59.8491 RMS 0.101966 Nphs 34 Gap 152.692 Dist 4.20134 Mamp -9.90 0 Mdur -9.90 0`

What should I look at first to assess the quality of this hypocenter calculation? And in particular, the Pmax (max. probability on grid) of 4.06675e+113, is that a good or bad location?

Thank you!
Catalina

**Comment by alomax** [comment]
Yes, I often use RMS, Nphs and Gap for filtering events on "quality". I also use the ellipsoid semi-major axis (Len3) from the STATISTICS line:

`STATISTICS  ExpectX 44.558015 Y -27.739417 Z 23.497832  CovXX 0.14082 XY 0.0467263 XZ 0.0314849 YY 0.127161 YZ 0.0168697 ZZ 0.167535 EllAz1  136.78 Dip1  -6.47508 Len1  0.550593 Az2  219.102 Dip2  49.6534 Len2  0.701853 Len3  8.611755e-01`

For plotting final location results, I usually use Len3 alone as a filter to trim the tail of poorest constrained locations. If Len3 is large, then the ellipsoid and PDF are highly elongated or generally very large.

Pmax, MFmin and MFmax are carried over from the original, grid-search version of NLLoc, these do not have much meaning, as they depend on the non-normalized likelihoods, I do not use these.

Best regards,
Anthony

**Comment by Cthuulhaa** [comment]
Thank you Anthony!

What would be in your experience an acceptable value for Len3, as well as for other relevant outputs, such as Gap?

Best,
Catalina

**Comment by alomax** [comment]
It depends on the scale of the study, the azimuth gap of available stations, and the quality of the picks.

For Len3, for precisely picked, local scale relocations (<20-30km study area) and good azimuth coverage, I may use Len3 as low as 2-5km; for large scale locations or poor station coverage or most stations far from the seismicity, I may use Len3 as high as 10-20km. Note that Len3 includes vertical uncertainty, which can be quite large in the latter cases.

For Gap, if azimuth coverage is very good, I may use as low as 90deg. But if the stations are off to one side, as with off-shore seismicity, I may use as much as 270deg. Greater than 180gap is best avoided, if possible, as this allows the events to move to/away from the station centroid with little change in residuals and overall apparent solution quality.

I usually do not set these filters too strong, as the goal is to remove clear outliers, not falsely bias the results to an apparent higher quality. Also, with station corrections (or NLL-SSST-coherence [https://doi.org/10.1029/2021JB023190](https://doi.org/10.1029/2021JB023190)) the relative position of hypocenters usually has much lower uncertainty than given by Len3, errH, errZ, RMS etc.

Anthony

**Comment by Cthuulhaa** [comment]
Thank you, Anthony!
