### ISSUE TITLE
stdint.h compilation issue

### ISSUE THREAD

**Issue by bakerb845** [alomax/NonLinLoc#13]
Hey Anthony, 

Unfortunately I'm using creaky, old centos7 and it doesn't know what int32_t is.

Can you add 

#include<stdint.h>  

or add an appropriate int32_t typedef 

in 

./src/io/jReadWrite/jWrite.h

I'm working off the latest commit (1cc76783bcc147ff27f6523f36b7ebfb04c50d35) Thanks!  - Ben

**Comment by alomax** [comment]
Hi Ben

There is already a line in jWrite.h:
`typedef unsigned int uint32_t;`
and there is no `int32_t`

Can you give me more details on what error you get?

Thanks,
Anthony

**Comment by bakerb845** [comment]
Sure thing, what I ended up doing was including stdint.h in jWrite.c.  Without it I get the following errors

[u6024448@notchpeak4:build]$ vi ..//io/jReadWrite/source/jWrite.c
[u6024448@notchpeak4:build]$ make
[  1%] Built target phaselist
Scanning dependencies of target GRID_LIB_OBJS
[  2%] Building C object CMakeFiles/GRID_LIB_OBJS.dir/io/jReadWrite/source/jWrite.c.o
/uufs/chpc.utah.edu/common/home/koper-group1/bbaker/daniel/cmake/NonLinLoc/src/io/jReadWrite/source/jWrite.c:45:18: error: unknown type name ‘int32_t’; did you mean ‘uint32_t’?
 void modp_itoa10(int32_t value, char* str);
                  ^~~~~~~
                  uint32_t
/uufs/chpc.utah.edu/common/home/koper-group1/bbaker/daniel/cmake/NonLinLoc/src/io/jReadWrite/source/jWrite.c: In function ‘jwObj_int’:
/uufs/chpc.utah.edu/common/home/koper-group1/bbaker/daniel/cmake/NonLinLoc/src/io/jReadWrite/source/jWrite.c:147:2: warning: implicit declaration of function ‘modp_itoa10’; did you mean ‘modp_dtoa2’? [-Wimplicit-function-declaration]
  modp_itoa10( value, JWC(tmpbuf) );
  ^~~~~~~~~~~
  modp_dtoa2
/uufs/chpc.utah.edu/common/home/koper-group1/bbaker/daniel/cmake/NonLinLoc/src/io/jReadWrite/source/jWrite.c: At top level:
/uufs/chpc.utah.edu/common/home/koper-group1/bbaker/daniel/cmake/NonLinLoc/src/io/jReadWrite/source/jWrite.c:408:18: error: unknown type name ‘int32_t’; did you mean ‘uint32_t’?
 void modp_itoa10(int32_t value, char* str)
                  ^~~~~~~
                  uint32_t
make[2]: *** [CMakeFiles/GRID_LIB_OBJS.dir/io/jReadWrite/source/jWrite.c.o] Error 1
make[1]: *** [CMakeFiles/GRID_LIB_OBJS.dir/all] Error 2
make: *** [all] Error 2

**Comment by alomax** [comment]
OK, I now see the problem. I added
`#include <stdint.h>`
in jWrite.c, and removed
`typedef unsigned int uint32_t;`
from jWrite.h

I will check if this is stable...

Thanks,
Anthony
