### ISSUE TITLE
Question: is the repository considered stable?

### ISSUE THREAD

**Issue by luca-s** [alomax/NonLinLoc#18]
Dear developers,

since I don't see releases for this repository (yet?) I wonder if the code is to be considered always stable, so that I can clone the master branch and use it right away, or if I should wait for a release to be published before making use of the code.

I can see at http://alomax.free.fr/nlloc/ that the last stable version is 7.00 and it is way older that this code. Also the beta version available there is older than this code.  So I am not sure when this code will be considered for a new release.

thanks
Luca

**Comment by alomax** [comment]
Hi Luca

The definitive version of NLL is in this repository. As there is no general funding for NLL, and no formal development/maintenance people besides me (!), there are little resources and time to organize, document and clean up the repository and software. I have just made a minor update to the doc and pushed the latest code (to `main`!).

So the code is never "stable" in the sense that there are not resources and people-power to properly maintain the project. But I only push to `main` code that I have run here in diverse tests and applications for some time, usually many months.
I would be happy to hear if you have suggestions for a quick and very easily maintainable manner to expand the repository to a release/dev architecture.

However, the documentation material at [http://alomax.free.fr/nlloc/](http://alomax.free.fr/nlloc/), though no longer updated, remains much more extensive than the new documentation (under development... spinning⏳) at [http://www.alomax.net/nlloc/docs](http://www.alomax.net/nlloc/docs).

**Comment by luca-s** [comment]
Thank you for your reply. I understand the lack of resources to make new releases. I have the same issue with the software I work with. Even though I try to commit to main only when the code is considered stable,  I would rather not mark a new release until I have gone trough an extensive and thorough testing phase. No testing -> no release! Sometime it takes forever to find the time to perform those tests. I have automated tests, which are convenient for spotting simple bugs, but they can cover only a minimum part of the code and I have a more robust suit of tests, which grow over time, that contains real world cases. Those latter tests give me high confidence of the code but they require manual evaluation/comparison with previous versions. So I do not run them  often, but when I do I tag the code and make a new release.

However your approach is good enough for me. I now know that you try to keep the main branch in a working state and if there are bugs, then I can always try to fix them and provide a PR.

**Comment by alomax** [comment]
Thanks for your comments. I do have several local scale and teleseismic tests, in addition to my own frequent use of NLL (always the latest developments), and questions/issues from many users. But the software has numerous modules and parameters, so ideally (but not realistically) the project should have quite an extensive suite of tests (and testers).

I updated [http://alomax.free.fr/nlloc/,](http://alomax.free.fr/nlloc/) to indicate that this repository gives the latest "release" and most recent, but sparse, documentation.

**Comment by luca-s** [comment]
> I updated [http://alomax.free.fr/nlloc/,](http://alomax.free.fr/nlloc/) to indicate that this repository gives the latest "release" and most recent, but sparse, documentation.

This is very useful, so there will be no more confusion on what is the latest version.

Minor issues:
- the web page has the link to version 7.00 of the software, but it points to version 6 (http://alomax.free.fr/nlloc/soft6.00)
- An icon is missing ![image](https://user-images.githubusercontent.com/15273575/168271607-53e0ac58-3e58-4db3-a62a-e4b1e4ee1b8c.png)

**Comment by alomax** [comment]
Thanks very much, fixed!
