### ISSUE TITLE
Is it possible to avoid loading the grid files into memory?

### ISSUE THREAD

**Issue by luca-s** [alomax/NonLinLoc#19]
Dear developers,

reading `GridLib.c` I noticed there is code that reads grid values from both a memory buffer or directly from disk files (`fseek` + `fread`). However I don't know how to select the behaviour via control file. Could you please point me to the configuration that controls this feature?

thanks
Luca

**Comment by alomax** [comment]
The only control for this is in 
`LOCMETH method maxDistStaGrid minNumberPhases maxNumberPhases minNumberSphases VpVsRatio maxNum3DGridMemory minDistStaGrid iRejectDuplicateArrivals`

`maxNum3DGridMemory` maximum number of 3D travel-time grids to attempt to read into memory. This helps to avoid time-consuming memory swapping that occurs if the total size of grids read exceeds the real memory of the computer. 3D grids not in memory are read directly from disk. If maxNum3DGridMemory < 0 then NLLoc attempts to read all grids into memory.

from [http://alomax.free.fr/nlloc/docs/programs/control.ControlFile.html](http://alomax.free.fr/nlloc/docs/programs/control.ControlFile.html)

The NLL code also does automatic loading into memory of slices of grids.
