### ISSUE TITLE
Question regarding "running the sample location tutorial"

### ISSUE THREAD

**Issue by rezkiaa** [alomax/NonLinLoc#20]
Hello, I am a newbie here and I would like to learn how to use the software. I have a question about running the sample location tutorial. I have installed the GMT plotting package. I tried to run the command:

Vel2Grid run/nlloc_sample.in (this one is OK)
Grid2GMT run/nlloc_sample.in model/layer.P.mod gmt/ V G 1 0 1 301
 
I got the following error:

Grid2GMT (NonLinLoc v7.00.00 27Oct2017) 

Processing files model/layer.P.mod.*
Output files gmt/layer.P.mod.VG.*
DEBUG: Grid3dFile: model/layer.P.mod, type:SLOW_LEN
INFO: cannot open hypocenter file: model/layer.P.mod.hyp
Generating Y section view...
44 rows and 301 columns written
LongitudeXX Section: 7.512704
Grid value min = 1.250000e-01,  value max = 2.500000e-01
INFO: cannot open station list file: model/layer.P.mod.stations
RVAL: RECT/X: 0.000000/300.000000 RECTY:-3.000000/40.000000
GetContourInterval htick_int R: GetContourInterval: vmin 0.00e+00 vmax 3.00e+02  contour_int 1.00e+02  nstep 4 
GetContourInterval vtick_int R: GetContourInterval: vmin -3.00e+00 vmax 4.00e+01  contour_int 1.00e+01  nstep 5 
GetContourInterval contour_int iFirstPlot: GetContourInterval: vmin 1.25e-01 vmax 2.50e-01  contour_int 1.00e-02  nstep 13 
INFO: makecpt -Z -Crainbow -T0.12/0.25/0.01 > gmt/layer.P.mod.VG.cpt

Running GMT script gmt/layer.P.mod.VG.gmt ...

sh: 1: gmt/layer.P.mod.VG.gmt: not found (this file is in the gmt folder, but I don't know why it isn't recognized)

I haven't yet successfully solved this issue. Could you tell me how to solve this problem?  Thank you beforehand

**Comment by rezkiaa** [comment]
Hello Anthony @alomax 

As for the script, I tried to run the tutorial from the folder I downloaded directly from your website (not the one from github). I ran the tutorial by copy/pasting each line in the script. I already checked the PATH environment, everything is already included in the environment. There is no problem with the permission too. 

When I ran the script "sh gmt/layer.P.mod.VG.gmt" in the folder "nlloc_sample", I got the following error:

gmt/layer.P.mod.VG.gmt: 5: gmtset: not found
gmt/layer.P.mod.VG.gmt: 7: gmtset: not found
gmt/layer.P.mod.VG.gmt: 9: gmtset: not found
unalias: rm not found
gmt/layer.P.mod.VG.gmt: 26: psbasemap: not found
gmt/layer.P.mod.VG.gmt: 35: psbasemap: not found
gmt/layer.P.mod.VG.gmt: 38: xyz2grd: not found
gmt/layer.P.mod.VG.gmt: 70: Syntax error: end of file unexpected (expecting "fi")

And if I ran "bash gmt/layer.P.mod.VG.gmt"

gmt/layer.P.mod.VG.gmt: line 5: gmtset: command not found
gmt/layer.P.mod.VG.gmt: line 7: gmtset: command not found
gmt/layer.P.mod.VG.gmt: line 9: gmtset: command not found
gmt/layer.P.mod.VG.gmt: line 13: unalias: rm: not found
gmt/layer.P.mod.VG.gmt: line 26: psbasemap: command not found
gmt/layer.P.mod.VG.gmt: line 35: psbasemap: command not found
gmt/layer.P.mod.VG.gmt: line 38: xyz2grd: command not found
gmt/layer.P.mod.VG.gmt: line 70: syntax error: unexpected end of file

Would it be better to use the tutorial from github?

**Comment by claudiodsf** [comment]
Which version of GMT do you use? 

Starting from GMT 5, all the commands must be preceded by `gmt`:
- `gmtset` --> `gmt set`
- `psbasemap` --> `gmt psbasemap`
- `xyz2grd` --> `gmt xyz2grd`

@alomax probably the NonLinLoc GMT interface should be updated (or simply deprecated?)

**Comment by alomax** [comment]
@rezkiaa
These errors are most likely due to the path to gmt4 not being on your environment PATH.

> @alomax probably the NonLinLoc GMT interface should be updated (or simply deprecated?)
It works fine with GMT4!
In my opinion, in a publicly funded research environment, all software should be 100% backwards compatible (e.g. GMT 5 and 6 and ... should support GMT 4 and 3 and 2 and 1). Or at least legacy installations should be very easy and should work. Alternatively, agencies funding research software development should insist and include extra funding to support updates to all the downstream research software that breaks when backwards compatibility is not provided.
Otherwise, we cannot talk about research reproducibility, nor there being much value in research funding for software development (as it will all break in 2-3 years.). This is no longer a personal rant - I have observed this problem too many times in action.

**Comment by claudiodsf** [comment]
Anthony, I see your point (and we already discussed it before 😉). The problem is that ensuring backwards compatibility costs resources, which publicly funded software development cannot always guarantee.

Having said that, GMT4 is still available for download here: https://github.com/GenericMappingTools/gmt/wiki/GMT-4.5.18

**Comment by alomax** [comment]
Another (much bigger?) problem is that fixing non-backwards compatibility costs resources, which publicly funded software development cannot always guarantee.

In general, I think that "*Move fast and break things*" is not healthy for science, completely incompatible with replicability, 
makes reproducibility difficult. What is the point of lots of time (and funding) preparing, documenting and distributing/archiving research software if the whole dependency house-of-cards is going to fall apart within a few years?


> Also, take a look [here](https://docs.generic-mapping-tools.org/6.1/switching.html) if you need different GMT versions to coexist on your machine.

Thanks. I do have a simple shell script to switch between 4 and 5. But I did knot know that:

> Because GMT 5 is backwards compatible with the 4.5.x series (provided you configured it that way)

I will have to look into this...

**Comment by rezkiaa** [comment]
Thank you very much for all the discussion.  I understand, I am currently using GMT6 so that must be the reason why I got this error. I will try to run the script again by using GMT4.

**Comment by rezkiaa** [comment]
Thank you very much for the suggestions!  Now, I can run the tutorial with GMT4, I will explore the program. 

I will close this comment.
