### ISSUE TITLE
TRANS_MERC: More flexibility to match custom UTM coordinate systems

### ISSUE THREAD

**Issue by megies** [alomax/NonLinLoc#22]
Hi Anthony,

thanks for your suggestions in #21, I was able now to get coordinate conversions tried out and I think we can pretty much use what is already built into NLLOC with a coordinate system for our models that makes sense for us.

There is only two (minor) problems right now:
 - a) false easting is hard coded (`off`) in the source code (edit: actually that's wrong, it has a default value `off` and will still be parsed, this last optional parameter is just not documented in the docs)
 - b) scale factor is hard coded (`1.0`)

Would you be open to an extension of the `TRANS_MERC` control file line to be able to specify these two? I'll make a PR real quick and you can have a look.

I'd like to use [the CRS that is used nowadays by our state geodetic and geologic services](https://epsg.io/25832) directly, to avoid confusion with coordinate conversions.

CC @jwassermann

**Comment by megies** [comment]
Also UTM CRS usually don't convert their coordinates to km, but this is just shifting the decimal point around, so It should not be confusing to leave it in km.

**Comment by alomax** [comment]
I could see changing the syntax to
`TRANS TRANS_MERC refEllipsoid latOrig longOrig rotAngle use_false_easting `false_easting` `scale_factor``
to maintain backwards compatibility, with defaults:
`use_false_easting = 0`
`false_easting = 500` or `false_easting = 500000` (have to check what is more consistent for NLL
`scale_factor = 1.0` or `scale_factor = 0.9996` (even though this will change previous results)
Is `scale_factor = 0.9996` correct for all UTM transverse Mercator?

Anthony

**Comment by megies** [comment]
> Is `scale_factor = 0.9996` correct for all UTM transverse Mercator?

No, there are some different values out there. I'll send a PR for some discussion about it tomorrow, already worked on it some :+1: 


> to maintain backwards compatibility, with defaults:

:+1:

**Comment by megies** [comment]
> `scale_factor = 1.0` or `scale_factor = 0.9996` (even though this will change previous results)

previous results will not be changed if we keep `1.0` as default
