### ISSUE TITLE
clarification on velocity model grid node centering

### ISSUE THREAD

**Issue by filefolder** [alomax/NonLinLoc#26]
Hi there, 

We're building velocity models and there is some slight confusion about whether or not the grid origins should be offset to the center of the grid. 

The text in the FAQ states: _The model file for Grid2Time must consist of cubic cells (dx = dy = dz) and the cell values must be SLOW_LEN  = slowness*length (sec) units, where length = dx. The cell values should correspond to the slowness at the center of each cell, e.g. the value at grid point x, y, z should be based on the slowness in the velocity model at x+dx/2, y + dy/2, z + dz/2._

So does this mean that this should be corrected via something like  `grd.x_orig -= grd.dx/2` or should the grid origin simply remain "on the model node" (e.g. 0). 

Thanks as always!

**Comment by alomax** [comment]
Hi

Yes, `grd.x_orig -= grd.dx/2` etc would be correct if grd refers to the velocity model grid. Grid2Time uses the Podvin Lecompte (1991) algorithm and code, which converts a slowness model consisting of constant values throughout each grid cell to travel-time at grid nodes. So if your velocity model is specified at nodes (as opposed to within cells), a -dx/2 etc shift to the velocity model grid origin is needed so the resulting travel-time grid values align correctly with the velocity model spatial origin.

Awfully confusing, I hope the above is correct...

Anthony
