### ISSUE TITLE
GMT version

### ISSUE THREAD

**Issue by SebasGamboa10** [alomax/NonLinLoc#32]
Hi, I´m having some problems using NonLinLoc, mainly with the tool GMT. I want to know if exist any restriction with the GMT version  for running NonLinLoc. I´m using  GMT v5.4.5 , does exist any problem with this version? Also, I was checking some files in this repo and I note that the used version is GMT v4.5.7 [64-bit].

 
%!PS-Adobe-3.0
%%BoundingBox: 0 0 595 842
%%HiResBoundingBox: 0 0 595 842
%%Title: GMT v4.5.7 [64-bit]
%%Creator: GMT
%%For: anthony
%%DocumentNeededResources: font Times-Roman
%%CreationDate: Fri May 13 09:14:12 2022
%%LanguageLevel: 2
%%DocumentData: Clean7Bit
%%Orientation: Portrait
%%Pages: 1
%%EndComments

Thanks for your help.

**Comment by alomax** [comment]
Yes, currently Grid2GMT works only with GMT 4. See https://github.com/alomax/NonLinLoc/issues/15
There may be an update to later versions of GMT soon, you could try the new code if your are interested: https://github.com/alomax/NonLinLoc/pull/30

Anthony

**Comment by SebasGamboa10** [comment]
Hi, thank you very much for your fast answer.
I used this repo for installing GMT 4: https://github.com/nestor-ld93/GMT4
Now it works great. 
Thank you.

**Comment by alomax** [comment]
Thanks.

It is also available here: [https://www.generic-mapping-tools.org/download/](https://www.generic-mapping-tools.org/download/)

(from 2019 and seems may drop off the list - 13 years is such a long time in science, what code, method or theory that old could still be of use! 🍎🌓🌍 #PerpetualBackwardsCompatibility)
