### ISSUE TITLE
Question: LOCGRID settings when LOCSEARCH is OCT

### ISSUE THREAD

**Issue by luca-s** [alomax/NonLinLoc#34]
Dear @alomax ,

I am not sure how I should consider the parameters of `LOCGRID` when `LOCSEARCH` is set to `OCT`. In particular, do the settings `dx dy dz` have an effect? I am asking this since the Octree method has its own settings to define the starting grid (`initNumCells_x initNumCells_y initNumCells_z`) and the following grids depends on the algorithm, not on `LOCGRID`. So I assume `LOCGRID` is used only to define the initial search volume, but the spacing of the grid is not relevant in the Octree scenario. Am I correct?

Also,a related question to `LOCGRID`  but not to Octree. What happens if the grid spacing defined on  `LOCGRID` is denser than the content of the grid files (e.g. the grid files were generated with a coarse grid settings): does the interpolation happen or it is an error?

thank you
Luca

**Comment by alomax** [comment]
Hi @luca-s 

You are correct, for oct-tree and Metropolis (deprecated) searchs the `LOCGRID` `dx dy dz` only serve to help define the location search volume extent. In the original version of NLLoc, the nested grid search algorithm required explicit setting of the cell sizes for each nested search grid - the `LOCGRID` parameters retain this convention.

In general, the travel-time grids are read with linear interpolation and independently from any grids defining working volumes. So, for example, a nested grid search does not have to have grid spacing that corresponds to the travel-time grids spacing. But if the travel-time grids are too coarse relative to the location constraint (e.g. pdf extent), then there may be interpolation errors that degrade to quality of the locations.

Anthony

**Comment by luca-s** [comment]
Thank you very much for the clarification.
