### ISSUE TITLE
Takeoff angle grid question

### ISSUE THREAD

**Issue by sboltz** [alomax/NonLinLoc#4]
Hello,

I use NonLinLoc pretty extensively for locating induced seismic events in shallow, heterogeneous environments. I tried to retrieve the takeoff angles from the grids by loading the grid using a python code that I have written. When I do this, the grid values that I see are on the order of 1e-30 - 1e-40, which doesn't make much sense to me. I know that my code works correctly because I can use it to load the velocity model or travel time grids without issue. Additionally, events locate reasonably, so I know I didn't do something grossly incorrect.

Is there something different about how the angle data is stored (I assume it should just be degrees?) compared to other grid outputs, or is there another setting that I need to change in the Grid2Time control file besides setting angleMode to ANGLES_YES?

I appreciate your help.

Thanks,
Shawn

**Comment by claudiodsf** [comment]
Takeoff angles are encoded in a C "union", so you need some trick to read them, as explained [here](http://alomax.free.fr/nlloc/soft7.00/formats.html#_grid_)

Take a look at my python implementation [nllgrid](https://github.com/claudiodsf/nllgrid) if you need some guidance 😉

**Comment by alomax** [comment]
Yes, @claudiodsf comments and links explain the angle encoding and how to access the values.
The purpose of this encoding is to fit 3 take-off values (quality, dip, azimuth) into a 4 byte float for compatibility with NLL velocity and time grids, and to save space in general.
Anthony

**Comment by sboltz** [comment]
Ah. Whoops. I should have finished reading the documentation.  That makes a lot more sense. Thank you for your help and quick response @claudiodsf and @alomax!
