### ISSUE TITLE
Generating take-off angles from precomputed 3D travel time grids

### ISSUE THREAD

**Issue by bhirao** [alomax/NonLinLoc#48]
Hi Anthony,

I have some 3D travel time grids that have been precomputed for use in NonLinLoc and GrowClust3d. We would like to compute grids of take-off angles for fault-plane solutions. I see that there is a Time2Angles module that can take the travel time grids and return take off angle grids. How might we set up the input file to use this? Or is there another way that might be better? We are using Version 7.0.

Many thanks,
Brenton

**Comment by alomax** [comment]
Hi Brenton,

I think `Time2Angles` would be best, it is made to do exactly what you want to do.

You need to add some `TA*` control statements to your NLL control file, for example:

```
# =============================================================================
# Time2Angles control file statements

# input, output filename root
# (TAFILES <input time file root> <output angles file root> wave_type (P, S))
#
TAFILES  /temp/nlloc_tmp/my_project/time_3d/time_root  /temp/nlloc_tmp/my_project/angles_3d/time_root P

# angles grid mode
# (TAMODE angle_mode)
#    (char[])   angle_mode (ANGLES_YES, ANGLES_NO, ANGLES_INCLINATION)
#
TAMODE ANGLES_YES

# source description (multiple sources can be specified)
# (TASRCE (see #GTSRCE)
#
==== Add TASRCE or GTSRCE sources here, individually or with INCLUDE ====

# END of Time2Angles control file statements
# =============================================================================

```

The control file statements required by `Time2Angles` are:
```
CONTROL, TRANS, TAMODE, TAFILES, TASRCE or GTSRCE
```

`INCLUDE` is also supported.

I have not used Time2Angles for many years, please tell me if there are problems...

Anthony

**Comment by bhirao** [comment]
Thank you, Anthony. This worked great!
