### ISSUE TITLE
Query NonLinLoc version string

### ISSUE THREAD

**Issue by yetinam** [alomax/NonLinLoc#54]
Hi @alomax ,
is there any way to query the NonLinLoc version string programatically? Something like `NLLoc --version`? I've integrated NonLinLoc into a larger earthquake catalog pipeline and would like to automatically track the versions of all tools I'm using.

**Comment by alomax** [comment]
Hi @yetinam 

I added -v and --version options to the NLLoc program command.
```
> NLLoc --version
NLLoc (NonLinLoc v7.1.04 05Sep2024)
```
I pushed this change to the dev  branch.
Other NLL programs do not (yet) have these options.

Is this sufficient for your current need?

Anthony

**Comment by yetinam** [comment]
Yes, that's exactly what I need. Thanks a lot for the quick addition!
