### ISSUE TITLE
GTFILES , generate P and S travel times simultaneously

### ISSUE THREAD

**Issue by Cthuulhaa** [alomax/NonLinLoc#8]
Hi!

I am testing NonLinLoc to locate local event. It works as expected, but I have until now executed Grid2Time twice: first to generate P travel times, then comment for P in the input control file and uncomment por S, then run Grid2Time again to generate S travel times. I want to use both P and S travel times for the location, but GTFILES is defined as non-repeatable.

Is it possible to generate P and S travel times in one run?

All the best,
Catalina

**Comment by alomax** [comment]
Hi @Cthuulhaa 

No, currently you have to run Grid2Time twice - this is on my list to change to repeatable...
If you need to run the program often, you could make a script (e.g. BASH) to add the GTFILES line with P and then S to a template control file, and run Grid2Time with the created control file.

Best regard,
Anthony

**Comment by Cthuulhaa** [comment]
Thank you, Anthony. I will close the issue now.

Cheers!
