### ISSUE TITLE
Density units of measurement

### ISSUE THREAD

**Issue by Cthuulhaa** [alomax/NonLinLoc#9]
Hi Anthony,

I see in the sample control file for the location of local events, in the parameter LAYER in the velocity model description, that the density is in kg/m^3. However, the values in this example are in g/cm^3. Density units are also described as in kg/m^3 in the documentation. Which density units of measurement are to be used?

Cheers,
Catalina

**Comment by alomax** [comment]
The density field is a carry over in the layer format from its original use in a waveform modelling code. The density is not used in the NLL programs, so you can put any convenient numeric values.

Anthony
